name: Deploy Nginx

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t custom-nginx:latest .

      - name: Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-nginx:latest'

      - name: Install Kind
        uses: helm/kind-action@v1.8.0

      - name: Create Kind Cluster
        run: |
          cat <<EOF | kind create cluster --config=-
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
            extraPortMappings:
            - containerPort: 80
              hostPort: 8080
          EOF

      - name: Verify Cluster and Create Namespace
        run: | 
          kubectl cluster-info
          kubectl config use-context kind-kind
          kubectl create ns nginx || echo "Namespace already exists"
          kubectl get ns nginx 
          kind load docker-image custom-nginx

      - name: Apply Nginx StatefulSet
        run: |
           kubectl apply -f k8-statefulset.yml -n nginx
           sleep 10
           kubectl get pods -n nginx -o wide
           echo "Waiting for Nginx pods to be in Running state..."
           kubectl wait --for=condition=Ready pod -l app=nginx --timeout=120s -n nginx
           kubectl get pods -n nginx -o wide

      - name: Debug - List All Resources
        run: |
          kubectl get all -A
          kubectl get statefulset -n nginx
          kubectl get pods -n nginx -o wide

      - name: Access Nginx Inside Pod
        run: |
          POD_NAME=$(kubectl get pod -l app=nginx -n nginx -o jsonpath="{.items[0].metadata.name}")
          echo "Accessing Nginx pod: $POD_NAME"
          kubectl exec $POD_NAME -n nginx -- curl -s http://localhost
