name: Deploy Nginx

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t my-nginx:latest .

      - name: Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-nginx:latest'

      - name: Install Kind
        uses: helm/kind-action@v1.8.0

      - name: Create Kind Cluster
        run: |
          cat <<EOF | kind create cluster --config=-
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
            extraPortMappings:
            - containerPort: 80
              hostPort: 8080
          EOF

      - name: Verify Cluster is Running
        run: | 
          kubectl cluster-info
          kubectl config use-context kind-kind

      - name: Apply Nginx StatefulSet
        run: |
           kubectl apply -f k8-statefulset.yml

      - name: Wait for Pods to be Running
        run: |
          echo "Waiting for Nginx pods to be in Running state..."
          kubectl wait --for=condition=Ready pod -l app=nginx --timeout=120s

      - name: List Pods
        run: kubectl get pods -o wide

      - name: Access Nginx Inside Pod
        run: |
          POD_NAME=$(kubectl get pod -l app=nginx -o jsonpath="{.items[0].metadata.name}")
          echo "Accessing Nginx pod: $POD_NAME"
          kubectl exec $POD_NAME -- curl -s http://localhost

      - name: Verify StatefulSet
        run: |
          kubectl get pods -l app=nginx
          kubectl get pvc
